sudo: false

language: php

php:
    - 7.1
    - 7.2

env:
    global:
        - SYMFONY_PHPUNIT_VERSION=6.5
        - SYMFONY_LOWEST=

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1
          env: SYMFONY_LOWEST="--prefer-lowest"

install:
    - composer install --prefer-dist
    - if [ "SYMFONY_LOWEST" != "" ]; then composer update symfony/security-bundle $SYMFONY_LOWEST --with-dependencies; fi

script:
    - composer test-ci

after_script:
    - composer test-publish
