image: php:7.2.2

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - cd /usr/local/bin && php -r "readfile('https://getcomposer.org/installer');" | php && mv composer.phar composer
          - apt-get update && apt-get install -y zlib1g-dev && docker-php-ext-install zip
          - composer install
          - vendor/bin/simple-phpunit
